{{- if .Values.backend.django.envSecret.create -}}
{{- $dbUrl := printf "%s://%s:%s@%s/%s" (include "paths.dbUrlScheme" .) .Values.db.user .Values.db.password (include "paths.dbClusterRwServiceName" .) .Values.db.database -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paths.backendDjangoEnvSecretName" . }}
type: Opaque
data:
  DATABASE_URL: {{ $dbUrl | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.db.password | b64enc }}
  SECRET_KEY: {{ .Values.backend.django.secretKey | b64enc }}
  AWS_ACCESS_KEY_ID: {{ .Values.backend.django.awsAccessKeyId | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.backend.django.awsSecretAccessKey | b64enc }}
{{- end -}}
