{{- if .Values.db.cluster.backup.s3Secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paths.dbBackupS3SecretName" . }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.db.cluster.backup.s3Secret.awsAccessKeyId | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.db.cluster.backup.s3Secret.awsSecretAccessKey | b64enc }}
{{- end -}}
