{{- /*
https://helm.sh/docs/howto/charts_tips_and_tricks/#creating-image-pull-secrets
*/ -}}
{{- if .Values.imagePullSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "watch.imagePullSecretName" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "watch.imagePullSecretData" . }}
{{- end -}}
