{{- if .Values.proxy.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
data:
  Caddyfile: |
    :{{ .Values.proxy.containerPort }}
        route /static/* {
            header Access-Control-Allow-Origin *
            header Access-Control-Allow-Headers *
            header Access-Control-Allow-Methods *
            uri strip_prefix /static
            root * {{ .Values.data.staticFiles }}
            file_server
        }
       route /media_files/* {
          header Access-Control-Allow-Origin *
          header Access-Control-Allow-Headers *
          header Access-Control-Allow-Methods *
          uri strip_prefix /media_files
          root * {{ .Values.data.mediaFiles }}
          file_server
        }

    reverse_proxy :{{ .Values.image.containerPort }}
{{- end -}}
