apiVersion: v1
kind: Service
metadata:
  name: {{ include "nextjs-helm.fullname" . }}
  labels:
    {{- include "nextjs-helm.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: nextjs
      protocol: TCP
      name: nextjs
    {{- if .Values.staticProxy.enabled }}
    - port: {{ .Values.staticProxy.servicePort }}
      targetPort: proxy
      protocol: TCP
      name: proxy
    {{- end }}
  selector:
    {{- include "nextjs-helm.selectorLabels" . | nindent 4 }}
