{{- if .Values.db.cluster.create -}}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "django-helm.dbClusterName" . }}
spec:
  instances: 3
  {{- if .Values.db.postgis }}
  imageName: ghcr.io/cloudnative-pg/postgis:13
  {{- else }}
  imageName: ghcr.io/cloudnative-pg/postgresql:13
  {{- end }}
  bootstrap:
    initdb:
      database: {{ .Values.db.database }}
      owner: {{ .Values.db.user }}
      secret:
        name: {{ include "django-helm.dbSecretName" . }}
      {{- if .Values.db.postgis }}
      postInitTemplateSQL:
        - CREATE EXTENSION postgis;
      {{- end }}
  # Example of rolling update strategy:
  # - unsupervised: automated update of the primary once all
  #                 replicas have been upgraded (default)
  # - supervised: requires manual supervision to perform
  #               the switchover of the primary
  primaryUpdateStrategy: unsupervised
  backup:
    target: prefer-standby
    retentionPolicy: "30d"
    barmanObjectStore:
      destinationPath: {{ .Values.db.cluster.backup.destinationPath }}
      endpointURL: {{ .Values.db.cluster.backup.endpointUrl }}
      s3Credentials:
        accessKeyId:
          name: {{ include "django-helm.dbBackupS3SecretName" . }}
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: {{ include "django-helm.dbBackupS3SecretName" . }}
          key: AWS_SECRET_ACCESS_KEY
  storage:
    size: 1Gi
{{- end -}}
